{-# LANGUAGE OverloadedStrings #-}

-- | Generated by hs-spacetime-codegen. Do not edit.
module Generated where

import Data.Int
import Data.Text (Text)
import Data.WideWord
import Data.Word
import SpacetimeDB.BSATN.Decoder
import SpacetimeDB.BSATN.Encoder
import SpacetimeDB.Client

data Widget = Widget
  { widgetId :: Word64
  , widgetName :: Text
  , widgetQuantity :: Word32
  }
  deriving (Eq, Show)

decodeWidget :: Decoder Widget
decodeWidget = Widget <$> u64 <*> string <*> u32

encodeWidget :: Encoder Widget
encodeWidget v = concatE [encodeU64 (widgetId v), encodeString (widgetName v), encodeU32 (widgetQuantity v)]

addWidget :: Client -> Text -> Word32 -> (ReducerReply () Text -> IO ()) -> IO ()
addWidget client arg0 arg1 cb =
  callReducer client "add_widget" (buildArgs [encodeString arg0, encodeU32 arg1]) (cb . reducerReply (pure ()) string)
