{-# LANGUAGE OverloadedStrings #-}

{- | Emit typed Haskell bindings from a parsed 'Module'. Output is
deterministic and fourmolu-clean: declared types become records with
decoders/encoders (sums become tagged unions), and each @ClientCallable@
reducer/procedure becomes a typed wrapper over the client call operations.
@Private@ callables are dropped silently.
-}
module SpacetimeDB.Codegen
  ( generate
  ) where

import Data.Char (toLower, toUpper)
import Data.List (find)
import qualified Data.Map.Strict as M
import Data.Maybe (mapMaybe)
import Data.Text (Text)
import qualified Data.Text as T
import SpacetimeDB.Codegen.Schema

{- | A type's Haskell rendering: the type expression, a decoder expression, and
an encoder-value expression (of type @Encoder a@).
-}
data Hs = Hs
  { hsType :: Text
  , hsDec :: Text
  , hsEnc :: Text
  }

{- | @generate skip m@ renders the module. On unsupported types it returns
'Left' with one message per offender, unless @skip@ is set, in which case the
offenders are recorded as @//// Skipped@ header lines and the rest is emitted.
-}
generate :: Bool -> Module -> Either [Text] Text
generate skip m
  | not skip && not (null dropMsgs) = Left dropMsgs
  | otherwise = Right (render skipHeader typeBlocks callableBlocks)
 where
  dropMsgs =
    [ name <> ": " <> reason
    | td <- modTypes m
    , let name = tdName td
    , Just reason <- [M.lookup (tdRef td) (modDropped m)]
    ]
  skipHeader = if skip then map ("//// Skipped " <>) dropMsgs else []
  typeBlocks = mapMaybe (typeBlock m) (modTypes m)
  callableBlocks =
    mapMaybe (reducerBlock m) (modReducers m)
      ++ mapMaybe (procedureBlock m) (modProcedures m)

-- Rendering ---------------------------------------------------------------

render :: [Text] -> [Text] -> [Text] -> Text
render skipHeader typeBlocks callableBlocks =
  T.unlines $
    ["{-# LANGUAGE OverloadedStrings #-}", ""]
      ++ prefixSkipComment skipHeader
      ++ [ "-- | Generated by hs-spacetime-codegen. Do not edit."
         , "module Generated where"
         , ""
         , "import Data.Int"
         , "import Data.Text (Text)"
         , "import Data.WideWord"
         , "import Data.Word"
         , "import SpacetimeDB.BSATN.Decoder"
         , "import SpacetimeDB.BSATN.Encoder"
         , "import SpacetimeDB.Client"
         ]
      ++ concatMap (\b -> "" : T.lines b) (typeBlocks ++ callableBlocks)
 where
  prefixSkipComment [] = []
  prefixSkipComment hs = hs ++ [""]

-- | A declared type: a record (product) or tagged union (sum).
typeBlock :: Module -> TypeDef -> Maybe Text
typeBlock m td = case bodyOf m (tdRef td) of
  Just (TProduct fields) -> Just (recordBlock m (tdName td) fields)
  Just (TSum variants) -> Just (sumBlock m (tdName td) variants)
  _ -> Nothing

recordBlock :: Module -> Text -> [Field] -> Text
recordBlock m name fields =
  T.unlines $
    [("data " <> ctor <> " = " <> ctor)]
      ++ recordFields
      ++ [ "  }"
         , "  deriving (Eq, Show)"
         , ""
         , decSig
         , decDef
         , ""
         , encSig
         , encDef
         ]
 where
  ctor = pascal name
  named = zipWith (fieldOf m name) [0 ..] fields
  recordFields = zipWith fieldLine (True : repeat False) named
  fieldLine first (fn, hs) =
    (if first then "  { " else "  , ") <> fn <> " :: " <> hsType hs
  decSig = "decode" <> ctor <> " :: Decoder " <> ctor
  decDef = "decode" <> ctor <> " = " <> ctor <> applied (map (hsDec . snd) named)
  encSig = "encode" <> ctor <> " :: Encoder " <> ctor
  encDef =
    "encode"
      <> ctor
      <> " v = concatE ["
      <> T.intercalate ", " [hsEnc hs <> " (" <> fn <> " v)" | (fn, hs) <- named]
      <> "]"

sumBlock :: Module -> Text -> [Field] -> Text
sumBlock m name variants =
  T.unlines $
    ("data " <> ctor)
      : zipWith variantLine (True : repeat False) vs
      ++ [ "  deriving (Eq, Show)"
         , ""
         , "decode" <> ctor <> " :: Decoder " <> ctor
         , "decode" <> ctor <> " = sumD $ \\t -> case t of"
         ]
      ++ [ "  " <> T.pack (show i) <> " -> Right (" <> vctor <> " <$> " <> hsDec hs <> ")"
         | (i, (vctor, hs)) <- zip [0 :: Int ..] vs
         ]
      ++ [ "  _ -> Left (UnknownVariant t)"
         , ""
         , "encode" <> ctor <> " :: Encoder " <> ctor
         , "encode" <> ctor <> " x = case x of"
         ]
      ++ [ "  " <> vctor <> " a -> encodeSum " <> T.pack (show i) <> " (" <> hsEnc hs <> " a)"
         | (i, (vctor, hs)) <- zip [0 :: Int ..] vs
         ]
 where
  ctor = pascal name
  vs = zipWith (variantOf m name) [0 ..] variants
  variantLine first (vctor, hs) =
    (if first then "  = " else "  | ") <> vctor <> " " <> hsType hs

variantOf :: Module -> Text -> Int -> Field -> (Text, Hs)
variantOf m tyName i (Field mn ty) =
  (pascal tyName <> pascal (maybe (T.pack ("Variant" ++ show i)) id mn), hsOf m ty)

fieldOf :: Module -> Text -> Int -> Field -> (Text, Hs)
fieldOf m tyName i (Field mn ty) =
  (camel tyName <> pascal (maybe (T.pack ("field" ++ show i)) id mn), hsOf m ty)

-- Callables ---------------------------------------------------------------

reducerBlock :: Module -> Reducer -> Maybe Text
reducerBlock m r
  | redVisibility r /= ClientCallable = Nothing
  | otherwise =
      Just $
        T.unlines
          [ fn <> " :: Client -> " <> argSig <> "(ReducerReply " <> okT <> " " <> errT <> " -> IO ()) -> IO ()"
          , fn <> " client " <> argBinders <> "cb ="
          , "  callReducer client \"" <> canonical <> "\" (buildArgs [" <> argEncs <> "]) (cb . reducerReply " <> okDec <> " " <> errDec <> ")"
          ]
 where
  fn = camel (redName r)
  canonical = M.findWithDefault (redName r) (redName r) (modCanonical m)
  args = zipWith (\i (Field _ ty) -> (T.pack ("arg" ++ show i), hsOf m ty)) [0 :: Int ..] (redParams r)
  argSig = T.concat [hsType hs <> " -> " | (_, hs) <- args]
  argBinders = T.concat [nm <> " " | (nm, _) <- args]
  argEncs = T.intercalate ", " [hsEnc hs <> " " <> nm | (nm, hs) <- args]
  (okT, okDec) = returnHs m (redOk r)
  (errT, errDec) = returnHs m (redErr r)

procedureBlock :: Module -> Procedure -> Maybe Text
procedureBlock m p
  | procVisibility p /= ClientCallable = Nothing
  | otherwise =
      Just $
        T.unlines
          [ fn <> " :: Client -> " <> argSig <> "(ProcedureReply " <> okT <> " -> IO ()) -> IO ()"
          , fn <> " client " <> argBinders <> "cb ="
          , "  callProcedure client \"" <> canonical <> "\" (buildArgs [" <> argEncs <> "]) (cb . procedureReply " <> okDec <> ")"
          ]
 where
  fn = camel (procName p)
  canonical = M.findWithDefault (procName p) (procName p) (modCanonical m)
  args = zipWith (\i (Field _ ty) -> (T.pack ("arg" ++ show i), hsOf m ty)) [0 :: Int ..] (procParams p)
  argSig = T.concat [hsType hs <> " -> " | (_, hs) <- args]
  argBinders = T.concat [nm <> " " | (nm, _) <- args]
  argEncs = T.intercalate ", " [hsEnc hs <> " " <> nm | (nm, hs) <- args]
  (okT, okDec) = returnHs m (procReturn p)

{- | The Haskell type + decoder for a reducer/procedure return position. A unit
product means @()@ decoded from an empty (or Ok-empty) payload.
-}
returnHs :: Module -> Typ -> (Text, Text)
returnHs _ (TProduct []) = ("()", "(pure ())")
returnHs m ty = let hs = hsOf m ty in (hsType hs, hsDec hs)

-- Type mapping ------------------------------------------------------------

hsOf :: Module -> Typ -> Hs
hsOf m ty = case ty of
  TPrim p -> primHs p
  TRef i -> case find ((== i) . tdRef) (modTypes m) of
    Just td -> let c = pascal (tdName td) in Hs c ("decode" <> c) ("encode" <> c)
    Nothing -> Hs "()" "(pure ())" "(const (concatE []))"
  TArray t ->
    let e = hsOf m t
     in Hs ("[" <> hsType e <> "]") ("(list " <> hsDec e <> ")") ("(encodeListOf " <> hsEnc e <> ")")
  TProduct [] -> Hs "()" "(pure ())" "(const (concatE []))"
  TProduct _ -> Hs "()" "(pure ())" "(const (concatE []))"
  s@(TSum _) -> case optionInner s of
    Just t ->
      let e = hsOf m t
       in Hs ("Maybe " <> hsType e) ("(optional " <> hsDec e <> ")") ("(encodeOptionalOf " <> hsEnc e <> ")")
    Nothing -> Hs "()" "(pure ())" "(const (concatE []))"

optionInner :: Typ -> Maybe Typ
optionInner (TSum [Field (Just "some") t, Field (Just "none") (TProduct [])]) = Just t
optionInner _ = Nothing

primHs :: Text -> Hs
primHs p = case p of
  "Bool" -> Hs "Bool" "bool" "encodeBool"
  "String" -> Hs "Text" "string" "encodeString"
  "U8" -> Hs "Word8" "u8" "encodeU8"
  "U16" -> Hs "Word16" "u16" "encodeU16"
  "U32" -> Hs "Word32" "u32" "encodeU32"
  "U64" -> Hs "Word64" "u64" "encodeU64"
  "U128" -> Hs "Word128" "u128" "encodeU128"
  "U256" -> Hs "Word256" "u256" "encodeU256"
  "I8" -> Hs "Int8" "i8" "encodeI8"
  "I16" -> Hs "Int16" "i16" "encodeI16"
  "I32" -> Hs "Int32" "i32" "encodeI32"
  "I64" -> Hs "Int64" "i64" "encodeI64"
  "I128" -> Hs "Int128" "i128" "encodeI128"
  "I256" -> Hs "Int256" "i256" "encodeI256"
  "F32" -> Hs "Float" "f32" "encodeF32"
  "F64" -> Hs "Double" "f64" "encodeF64"
  other -> Hs other ("undefined {- " <> other <> " -}") "(const (concatE []))"

bodyOf :: Module -> Int -> Maybe Typ
bodyOf m r = case drop r (modTypespace m) of
  (t : _) | r >= 0 -> Just t
  _ -> Nothing

applied :: [Text] -> Text
applied [] = ""
applied (d : ds) = " <$> " <> d <> T.concat [" <*> " <> x | x <- ds]

-- Name helpers ------------------------------------------------------------

pascal :: Text -> Text
pascal = T.concat . map cap . splitParts
 where
  cap w = case T.uncons w of
    Just (c, rest) -> T.cons (toUpper c) rest
    Nothing -> w

camel :: Text -> Text
camel t = case pascal t of
  s -> case T.uncons s of
    Just (c, rest) -> T.cons (toLower c) rest
    Nothing -> s

splitParts :: Text -> [Text]
splitParts = filter (not . T.null) . T.split (\c -> c == '_' || c == ' ' || c == '-')
